Algoritmo "EXERCICIO SOMA 2 NUM. INT"
// Fazer um programa para ler dois valores inteiros X e Y,
//e depois mostrar na tela o valor da soma destes números.
Var
// Seção de Declarações das variáveis 
    x, y, soma :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Informe o valor de 'X': ")
     leia(x)
     escreva("Informe o valor de 'Y': ")
     leia(y)
     
     soma <- x + y
     
     escreva("SOMA = ",soma)

Fimalgoritmo