Algoritmo "Exemplo Tabuada"
//  LER UM NUMERO INTEIRO E MOSTRAR NA TELA A TABUADA DO NUMERO DE 1 A 10.

Var

 num,i, resultado: inteiro


Inicio

      escreval("Para qual número você deseja a tabuada? ")
      leia(num)
      

      para i de 0 ate 10 faca
      
      resultado <- num * i
      escreval(num," X ",i, " = ",resultado)

      
      
      fimpara



Fimalgoritmo